#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v10
# autospec commit: 5905be9
#
Name     : perl-Object-Remote
Version  : 0.004004
Release  : 18
URL      : https://cpan.metacpan.org/authors/id/H/HA/HAARG/Object-Remote-0.004004.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/H/HA/HAARG/Object-Remote-0.004004.tar.gz
Summary  : 'Call methods on objects in other processes or on other hosts'
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-1.0
Requires: perl-Object-Remote-bin = %{version}-%{release}
Requires: perl-Object-Remote-license = %{version}-%{release}
Requires: perl-Object-Remote-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Algorithm::C3)
BuildRequires : perl(Class::C3)
BuildRequires : perl(Class::Method::Modifiers)
BuildRequires : perl(Data::Dumper::Concise)
BuildRequires : perl(Devel::GlobalDestruction)
BuildRequires : perl(Future)
BuildRequires : perl(Log::Contextual)
BuildRequires : perl(MRO::Compat)
BuildRequires : perl(Module::Runtime)
BuildRequires : perl(Moo)
BuildRequires : perl(Role::Tiny)
BuildRequires : perl(String::ShellQuote)
BuildRequires : perl(Sub::Exporter::Progressive)
BuildRequires : perl(Sub::Quote)
BuildRequires : perl(Test::Fatal)
BuildRequires : perl(Try::Tiny)
BuildRequires : perl(strictures)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
NAME
Object::Remote - Call methods on objects in other processes or on other
hosts

%package bin
Summary: bin components for the perl-Object-Remote package.
Group: Binaries
Requires: perl-Object-Remote-license = %{version}-%{release}

%description bin
bin components for the perl-Object-Remote package.


%package dev
Summary: dev components for the perl-Object-Remote package.
Group: Development
Requires: perl-Object-Remote-bin = %{version}-%{release}
Provides: perl-Object-Remote-devel = %{version}-%{release}
Requires: perl-Object-Remote = %{version}-%{release}

%description dev
dev components for the perl-Object-Remote package.


%package license
Summary: license components for the perl-Object-Remote package.
Group: Default

%description license
license components for the perl-Object-Remote package.


%package perl
Summary: perl components for the perl-Object-Remote package.
Group: Default
Requires: perl-Object-Remote = %{version}-%{release}

%description perl
perl components for the perl-Object-Remote package.


%prep
%setup -q -n Object-Remote-0.004004
cd %{_builddir}/Object-Remote-0.004004
pushd ..
cp -a Object-Remote-0.004004 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Object-Remote
cp %{_builddir}/Object-Remote-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-Object-Remote/8e66294e05cb01b0a01f8ae91d3aad268d8906b2 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/object-remote-node
/usr/bin/object-remote-slave
/usr/bin/remoterepl

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Object::Remote.3
/usr/share/man/man3/Object::Remote::Connection.3
/usr/share/man/man3/Object::Remote::Future.3
/usr/share/man/man3/Object::Remote::Logging.3
/usr/share/man/man3/Object::Remote::Logging::Logger.3
/usr/share/man/man3/Object::Remote::Role::Connector::PerlInterpreter.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Object-Remote/8e66294e05cb01b0a01f8ae91d3aad268d8906b2

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
